import { Inter } from "next/font/google";
import { createTheme, MantineProvider } from '@mantine/core';
import Navigation from '../components/Navigation/Navigation';
import "./globals.css";
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Navigation />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
